apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
  namespace: cloudlab
  labels:
    app: ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
        - name: ocr
          image: ghcr.io/harkaibalazs/ocr:v0.1.3
          env:
            - name: RABBITMQ_URL
              value: amqp://cloudlab:cloudlab@rabbitmq.internal.svc.cluster.local:5672/%2F
            - name: RABBITMQ_EXCHANGE
              value: events
            - name: RABBITMQ_QUEUE
              value: ocr_worker
            - name: REDIS_URL
              value: redis://redis.redis-server.svc.cluster.local:6379/0
            - name: TESSERACT_LANGS
              value: eng+chi_sim
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
