apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: cloudlab
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/harkaibalazs/web:v0.1.1
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_URL
              value: redis://redis.redis-server.svc.cluster.local:6379/0
            - name: RABBITMQ_URL
              value: amqp://cloudlab:cloudlab@rabbitmq.internal.svc.cluster.local:5672/%2F
            - name: RABBITMQ_EXCHANGE
              value: events
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
