name: Build and push

on:
  push:
    branches:
      - main
    paths:
      - ocr/**
      - .github/workflows/build-ocr.yml
    tags:
      - "ocr-v*.*.*"
  workflow_dispatch:


permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/ocr
  MANIFEST_PATH: manifests/ocr-deploy.yaml


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=ocr-(v\d+\.\d+\.\d+),group=1
            type=match,pattern=ocr-v(\d+\.\d+),group=1,prefix=v
            type=match,pattern=ocr-v(\d+),group=1,prefix=v
            type=ref,event=branch
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/ocr-v') }}
            type=raw,value=dev,enable={{is_default_branch}}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login to Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4


      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64
          context: ./ocr
          file: ./ocr/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: ["build_and_push"]
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=ocr-(v\d+\.\d+\.\d+),group=1

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Update Kubernetes manifest with new image
        run: |
          echo "Updating deployment manifest image to ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}"
          sed -i "s|image:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}|g" ${{ env.MANIFEST_PATH }}

      - name: Commit updated manifest
        run: |
          git config user.name "github_actions"
          git config user.email "actions@github.com"
          git add ${{ env.MANIFEST_PATH }}
          git commit -m "Update image version to ${{ steps.meta.outputs.version }}" || echo "No changes to commit"
          git push
